apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Scale when cpu > 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50 # Scale when memory > 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50     # Scale down max 50% pods at once
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0 # Scale up immediately
      policies:
      - type: Percent
        value: 100    # Can double pods at once
        periodSeconds: 15


      
