apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: haycuulaytoi/htxh-backend-arm64:latest
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: be-config
          - secretRef:
              name: be-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
